import { League_Spartan } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = League_Spartan({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.className}  antialiased`}>{children}</body>
    </html>
  );
}
